variables:
    DEBIAN_DEPS:
      build-essential
      bison
      flex
      gnome-common
      intltool
      itstool
      libgcr-3-dev
      libglib2.0-dev
      libgtk-3-dev
      libkrb5-dev
      libpam0g-dev
      meson
      pkg-config
      yelp-tools

build-debian:
  image: debian:bullseye
  stage: build
  before_script:
    - apt-get update
    - apt-get -y install $DEBIAN_DEPS
  script:
    - meson . _build
    - ninja -C _build
