include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

variables:
    DEBIAN_DEPS:
      build-essential
      bison
      flex
      gnome-common
      intltool
      itstool
      libgcr-3-dev
      libglib2.0-dev
      libgtk-3-dev
      libkrb5-dev
      libpam0g-dev
      meson
      pkg-config
      yelp-tools

build-debian:
  image: debian:bullseye
  stage: build
  before_script:
    - apt-get update
    - apt-get -y install $DEBIAN_DEPS
  script:
    - meson . _build
    - ninja -C _build

flatpak:
  image: registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master
  stage: build
  variables:
    MANIFEST_PATH: 'org.gnome.KrbAuthDialog.json'
    FLATPAK_MODULE: "org.gnome.KrbAuthDialog"
    RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
    APP_ID: "org.gnome.KrbAuthDialog"
    BUNDLE: 'org.gnome.KrbAuthDialog.flatpak'
  extends: .flatpak

