variables:
    DEBIAN_DEPS:
      autoconf
      automake
      build-essential
      bison
      flex
      gnome-common
      intltool
      itstool
      libglib2.0-dev
      libgtk-3-dev
      libkrb5-dev
      libnm-dev
      libpam0g-dev
      pkg-config
      yelp-tools

build-debian:
  image: debian:bullseye
  stage: build
  before_script:
    - apt-get update
    - apt-get -y install $DEBIAN_DEPS
  script:
    - ./autogen.sh
    - make
