/* This file is generated by hand from kerberos 1.3.4 by running
 *
 * ./etpo /path/to/krb5-1.3.4/ > dummy-strings.c
 *
 * It was then stripped of the meaningless messages (such as "Reserved
 * error message [60-254]").  It is expected that not all these
 * messages are translated.
 */

#include <glib/gi18n.h>

const char *dummy[] = {
	N_("Can't read ticket file"),	/* test1.et:krb:KRB_MK_AP_TKFIL */
	N_("Can't find ticket or TGT"),	/* test1.et:krb:KRB_MK_AP_NOTKT */
	N_("TGT expired"),	/* test1.et:krb:KRB_MK_AP_TGTEXP */
	N_("Can't decode authenticator"),	/* test1.et:krb:KRB_RD_AP_UNDEC */
	N_("Ticket expired"),	/* test1.et:krb:KRB_RD_AP_EXP */
	N_("Repeated request"),	/* test1.et:krb:KRB_RD_AP_REPEAT */
	N_("The ticket isn't for us"),	/* test1.et:krb:KRB_RD_AP_NOT_US */
	N_("Request is inconsistent"),	/* test1.et:krb:KRB_RD_AP_INCON */
	N_("Delta-T too big"),	/* test1.et:krb:KRB_RD_AP_TIME */
	N_("Incorrect net address"),	/* test1.et:krb:KRB_RD_AP_BADD */
	N_("Protocol version mismatch"),	/* test1.et:krb:KRB_RD_AP_VERSION */
	N_("Invalid message type"),	/* test1.et:krb:KRB_RD_AP_MSG_TYPE */
	N_("Message stream modified"),	/* test1.et:krb:KRB_RD_AP_MODIFIED */
	N_("Message out of order"),	/* test1.et:krb:KRB_RD_AP_ORDER */
	N_("Unauthorized request"),	/* test1.et:krb:KRB_RD_AP_UNAUTHOR */
	N_("Current password is null"),	/* test1.et:krb:KRB_GT_PW_NULL */
	N_("Incorrect current password"),	/* test1.et:krb:KRB_GT_PW_BADPW */
	N_("Protocol error"),	/* test1.et:krb:KRB_GT_PW_PROT */
	N_("Error returned by KDC"),	/* test1.et:krb:KRB_GT_PW_KDCERR */
	N_("Null ticket returned by KDC"),	/* test1.et:krb:KRB_GT_PW_NULLTKT */
	N_("Retry count exceeded"),	/* test1.et:krb:KRB_SKDC_RETRY */
	N_("Can't send request"),	/* test1.et:krb:KRB_SKDC_CANT */
	N_("Subsystem aborted"),	/* ss_err.et:ss:SS_ET_SUBSYSTEM_ABORTED */
	N_("Version mismatch"),	/* ss_err.et:ss:SS_ET_VERSION_MISMATCH */
	N_("No current invocation"),	/* ss_err.et:ss:SS_ET_NULL_INV */
	N_("No info directory"),	/* ss_err.et:ss:SS_ET_NO_INFO_DIR */
	N_("Command not found"),	/* ss_err.et:ss:SS_ET_COMMAND_NOT_FOUND */
	N_("Command line aborted"),	/* ss_err.et:ss:SS_ET_LINE_ABORTED */
	N_("End-of-file reached"),	/* ss_err.et:ss:SS_ET_EOF */
	N_("Permission denied"),	/* ss_err.et:ss:SS_ET_PERMISSION_DENIED */
	N_("Request table not found"),	/* ss_err.et:ss:SS_ET_TABLE_NOT_FOUND */
	N_("No info available"),	/* ss_err.et:ss:SS_ET_NO_HELP_FILE */
	N_("Shell escapes are disabled"),	/* ss_err.et:ss:SS_ET_ESCAPE_DISABLED */
	N_("Sorry, this request is not yet implemented"),	/* ss_err.et:ss:SS_ET_UNIMPLEMENTED */
	N_("Profile version 0.0"),	/* prof_err.et:prof:PROF_VERSION */
	N_("Bad magic value in profile_node"),	/* prof_err.et:prof:PROF_MAGIC_NODE */
	N_("Profile section not found"),	/* prof_err.et:prof:PROF_NO_SECTION */
	N_("Profile relation not found"),	/* prof_err.et:prof:PROF_NO_RELATION */
	N_("Attempt to add a relation to node which is not a section"),	/* prof_err.et:prof:PROF_ADD_NOT_SECTION */
	N_("A profile section header has a non-zero value"),	/* prof_err.et:prof:PROF_SECTION_WITH_VALUE */
	N_("Bad linked list in profile structures"),	/* prof_err.et:prof:PROF_BAD_LINK_LIST */
	N_("Bad group level in profile strctures"),	/* prof_err.et:prof:PROF_BAD_GROUP_LVL */
	N_("Bad parent pointer in profile strctures"),	/* prof_err.et:prof:PROF_BAD_PARENT_PTR */
	N_("Bad magic value in profile iterator"),	/* prof_err.et:prof:PROF_MAGIC_ITERATOR */
	N_("Can't set value on section node"),	/* prof_err.et:prof:PROF_SET_SECTION_VALUE */
	N_("Invalid argument passed to profile library"),	/* prof_err.et:prof:PROF_EINVAL */
	N_("Attempt to modify read-only profile"),	/* prof_err.et:prof:PROF_READ_ONLY */
	N_("Profile section header not at top level"),	/* prof_err.et:prof:PROF_SECTION_NOTOP */
	N_("Syntax error in profile section header"),	/* prof_err.et:prof:PROF_SECTION_SYNTAX */
	N_("Syntax error in profile relation"),	/* prof_err.et:prof:PROF_RELATION_SYNTAX */
	N_("Extra closing brace in profile"),	/* prof_err.et:prof:PROF_EXTRA_CBRACE */
	N_("Missing open brace in profile"),	/* prof_err.et:prof:PROF_MISSING_OBRACE */
	N_("Bad magic value in profile_t"),	/* prof_err.et:prof:PROF_MAGIC_PROFILE */
	N_("Bad magic value in profile_section_t"),	/* prof_err.et:prof:PROF_MAGIC_SECTION */
	N_("Iteration through all top level section not supported"),	/* prof_err.et:prof:PROF_TOPSECTION_ITER_NOSUPP */
	N_("Invalid profile_section object"),	/* prof_err.et:prof:PROF_INVALID_SECTION */
	N_("No more sections"),	/* prof_err.et:prof:PROF_END_OF_SECTIONS */
	N_("Bad nameset passed to query routine"),	/* prof_err.et:prof:PROF_BAD_NAMESET */
	N_("No profile file open"),	/* prof_err.et:prof:PROF_NO_PROFILE */
	N_("Bad magic value in profile_file_t"),	/* prof_err.et:prof:PROF_MAGIC_FILE */
	N_("Couldn't open profile file"),	/* prof_err.et:prof:PROF_FAIL_OPEN */
	N_("Section already exists"),	/* prof_err.et:prof:PROF_EXISTS */
	N_("Invalid boolean value"),	/* prof_err.et:prof:PROF_BAD_BOOLEAN */
	N_("Invalid integer value"),	/* prof_err.et:prof:PROF_BAD_INTEGER */
	N_("Bad magic value in profile_file_data_t"),	/* prof_err.et:prof:PROF_MAGIC_FILE_DATA */
	N_("Failed to unlock or grant streams pty."),	/* pty_err.et:pty:PTY_GETPTY_STREAMS */
	N_("fstat of master pty failed"),	/* pty_err.et:pty:PTY_GETPTY_FSTAT */
	N_("All terminal ports in use"),	/* pty_err.et:pty:PTY_GETPTY_NOPTY */
	N_("buffer to hold slave pty name is too short"),	/* pty_err.et:pty:PTY_GETPTY_SLAVE_TOOLONG */
	N_("Failed to open slave side of pty"),	/* pty_err.et:pty:PTY_OPEN_SLAVE_OPENFAIL */
	N_("Failed to chmod slave side of pty"),	/* pty_err.et:pty:PTY_OPEN_SLAVE_CHMODFAIL */
	N_("Unable to set controlling terminal"),	/* pty_err.et:pty:PTY_OPEN_SLAVE_NOCTTY */
	N_("Failed to chown slave side of pty"),	/* pty_err.et:pty:PTY_OPEN_SLAVE_CHOWNFAIL */
	N_("Call to line_push failed to push streams on slave pty"),	/* pty_err.et:pty:PTY_OPEN_SLAVE_LINE_PUSHFAIL */
	N_("Failed to push stream on slave side of pty"),	/* pty_err.et:pty:PTY_OPEN_SLAVE_PUSH_FAIL */
	N_("Failed to revoke slave side of pty"),	/* pty_err.et:pty:PTY_OPEN_SLAVE_REVOKEFAIL */
	N_("bad process type passed to pty_update_utmp"),	/* pty_err.et:pty:PTY_UPDATE_UTMP_PROCTYPE_INVALID */
	N_("Slave pty name is zero-length"),	/* pty_err.et:pty:PTY_OPEN_SLAVE_TOOSHORT */
	N_("Usage: kpasswd [principal_name]."),	/* kpasswd_strings.et:kpws:KPW_STR_USAGE */
	N_("Kerberos principal name %s is not recognized."),	/* kpasswd_strings.et:kpws:KPW_STR_PRIN_UNKNOWN */
	N_("while reading principal name from credential cache."),	/* kpasswd_strings.et:kpws:KPW_STR_WHILE_LOOKING_AT_CC */
	N_("Old Kerberos password is incorrect. Please try again."),	/* kpasswd_strings.et:kpws:KPW_STR_OLD_PASSWORD_INCORRECT */
	N_("Cannot establish a session with the Kerberos administrative server for\n\
realm %s. %s."),	/* kpasswd_strings.et:kpws:KPW_STR_CANT_OPEN_ADMIN_SERVER */
	N_("New passwords do not match - password not changed.\n"),	/* kpasswd_strings.et:kpws:KPW_STR_NEW_PASSWORD_MISMATCH */
	N_("Kerberos password changed.\n"),	/* kpasswd_strings.et:kpws:KPW_STR_PASSWORD_CHANGED */
	N_("Password not changed."),	/* kpasswd_strings.et:kpws:KPW_STR_PASSWORD_NOT_CHANGED */
	N_("when parsing name %s."),	/* kpasswd_strings.et:kpws:KPW_STR_PARSE_NAME */
	N_("when unparsing name."),	/* kpasswd_strings.et:kpws:KPW_STR_UNPARSE_NAME */
	N_("Unable to identify user from password file."),	/* kpasswd_strings.et:kpws:KPW_STR_NOT_IN_PASSWD_FILE */
	N_("Changing password for %s."),	/* kpasswd_strings.et:kpws:KPW_STR_CHANGING_PW_FOR */
	N_("Old password"),	/* kpasswd_strings.et:kpws:KPW_STR_OLD_PASSWORD_PROMPT */
	N_("while reading new password."),	/* kpasswd_strings.et:kpws:KPW_STR_WHILE_READING_PASSWORD */
	N_("You must type a password. Passwords must be at least one character long."),	/* kpasswd_strings.et:kpws:KPW_STR_NO_PASSWORD_READ */
	N_("while trying to change password."),	/* kpasswd_strings.et:kpws:KPW_STR_WHILE_TRYING_TO_CHANGE */
	N_("while closing session with admin server and destroying tickets."),	/* kpasswd_strings.et:kpws:KPW_STR_WHILE_DESTROYING_ADMIN_SESSION */
	N_("while freeing admin principal entry"),	/* kpasswd_strings.et:kpws:KPW_STR_WHILE_FREEING_PRINCIPAL */
	N_("while freeing admin policy entry"),	/* kpasswd_strings.et:kpws:KPW_STR_WHILE_FREEING_POLICY */
	N_("Could not get password policy information for principal %s."),	/* kpasswd_strings.et:kpws:KPW_STR_CANT_GET_POLICY_INFO */
	N_("%s's password is controlled by the policy %s, which\nrequires a minimum of %u characters from at least %u classes (the five classes\nare lowercase, uppercase, numbers, punctuation, and all other characters)."),	/* kpasswd_strings.et:kpws:KPW_STR_POLICY_EXPLANATION */
	N_("Successfully imported %d record%s.\n"),	/* import_err.et:imp:IMPORT_NO_ERR */
	N_("Input not recognized as database dump"),	/* import_err.et:imp:IMPORT_BAD_FILE */
	N_("Bad token in dump file."),	/* import_err.et:imp:IMPORT_BAD_TOKEN */
	N_("Bad version in dump file"),	/* import_err.et:imp:IMPORT_BAD_VERSION */
	N_("Defective record encountered: "),	/* import_err.et:imp:IMPORT_BAD_RECORD */
	N_("Truncated input file detected."),	/* import_err.et:imp:IMPORT_BAD_FOOTER */
	N_("Import of dump failed"),	/* import_err.et:imp:IMPORT_FAILED */
	N_("Mismatched record count: %d record%s indicated, %d record%s scanned.\n"),	/* import_err.et:imp:IMPORT_COUNT_MESSAGE */
	N_("Number of records imported does not match count"),	/* import_err.et:imp:IMPORT_MISMATCH_COUNT */
	N_("Unknown command line option.\nUsage: ovsec_adm_import [filename]"),	/* import_err.et:imp:IMPORT_UNK_OPTION */
	N_("Warning -- continuing to import will overwrite existing databases!"),	/* import_err.et:imp:IMPORT_WARN_DB */
	N_("Database rename Failed!!"),	/* import_err.et:imp:IMPORT_RENAME_FAILED */
	N_("Extra data after footer is ignored."),	/* import_err.et:imp:IMPORT_EXTRA_DATA */
	N_("Proceed <y|n>?"),	/* import_err.et:imp:IMPORT_CONFIRM */
	N_("while opening input file"),	/* import_err.et:imp:IMPORT_OPEN_DUMP */
	N_("while importing databases"),	/* import_err.et:imp:IMPORT_IMPORT */
	N_("cannot open /dev/tty!!"),	/* import_err.et:imp:IMPORT_TTY */
	N_("while opening databases"),	/* import_err.et:imp:IMPORT_RENAME_OPEN */
	N_("while acquiring permanent lock"),	/* import_err.et:imp:IMPORT_RENAME_LOCK */
	N_("while releasing permanent lock"),	/* import_err.et:imp:IMPORT_RENAME_UNLOCK */
	N_("while closing databases"),	/* import_err.et:imp:IMPORT_RENAME_CLOSE */
	N_("while retrieving configuration parameters"),	/* import_err.et:imp:IMPORT_GET_PARAMS */
	N_("$Id$"),	/* kdc5_err.et:kdc5:KDC5_RCSID */
	N_("No server port found"),	/* kdc5_err.et:kdc5:KDC5_NOPORT */
	N_("Network not initialized"),	/* kdc5_err.et:kdc5:KDC5_NONET */
	N_("Short write while sending response"),	/* kdc5_err.et:kdc5:KDC5_IO_RESPONSE */
	N_("Cannot convert V5 keyblock"),	/* krb524_err.et:k524:KRB524_BADKEY */
	N_("Cannot convert V5 address information"),	/* krb524_err.et:k524:KRB524_BADADDR */
	N_("Cannot convert V5 principal"),	/* krb524_err.et:k524:KRB524_BADPRINC */
	N_("V5 realm name longer than V4 maximum"),	/* krb524_err.et:k524:KRB524_BADREALM */
	N_("Kerberos V4 error"),	/* krb524_err.et:k524:KRB524_V4ERR */
	N_("Encoding too large"),	/* krb524_err.et:k524:KRB524_ENCFULL */
	N_("Decoding out of data"),	/* krb524_err.et:k524:KRB524_DECEMPTY */
	N_("Service not responding"),	/* krb524_err.et:k524:KRB524_NOTRESP */
	N_("Kerberos version 4 support is disabled"),	/* krb524_err.et:k524:KRB524_KRB4_DISABLED */
	N_("No error"),	/* krb5_err.et:krb5:KRB5KDC_ERR_NONE */
	N_("Client's entry in database has expired"),	/* krb5_err.et:krb5:KRB5KDC_ERR_NAME_EXP */
	N_("Server's entry in database has expired"),	/* krb5_err.et:krb5:KRB5KDC_ERR_SERVICE_EXP */
	N_("Requested protocol version not supported"),	/* krb5_err.et:krb5:KRB5KDC_ERR_BAD_PVNO */
	N_("Client's key is encrypted in an old master key"),	/* krb5_err.et:krb5:KRB5KDC_ERR_C_OLD_MAST_KVNO */
	N_("Server's key is encrypted in an old master key"),	/* krb5_err.et:krb5:KRB5KDC_ERR_S_OLD_MAST_KVNO */
	N_("Client not found in Kerberos database"),	/* krb5_err.et:krb5:KRB5KDC_ERR_C_PRINCIPAL_UNKNOWN */
	N_("Server not found in Kerberos database"),	/* krb5_err.et:krb5:KRB5KDC_ERR_S_PRINCIPAL_UNKNOWN */
	N_("Principal has multiple entries in Kerberos database"),	/* krb5_err.et:krb5:KRB5KDC_ERR_PRINCIPAL_NOT_UNIQUE */
	N_("Client or server has a null key"),	/* krb5_err.et:krb5:KRB5KDC_ERR_NULL_KEY */
	N_("Ticket is ineligible for postdating"),	/* krb5_err.et:krb5:KRB5KDC_ERR_CANNOT_POSTDATE */
	N_("Requested effective lifetime is negative or too short"),	/* krb5_err.et:krb5:KRB5KDC_ERR_NEVER_VALID */
	N_("KDC policy rejects request"),	/* krb5_err.et:krb5:KRB5KDC_ERR_POLICY */
	N_("KDC can't fulfill requested option"),	/* krb5_err.et:krb5:KRB5KDC_ERR_BADOPTION */
	N_("KDC has no support for encryption type"),	/* krb5_err.et:krb5:KRB5KDC_ERR_ETYPE_NOSUPP */
	N_("KDC has no support for checksum type"),	/* krb5_err.et:krb5:KRB5KDC_ERR_SUMTYPE_NOSUPP */
	N_("KDC has no support for padata type"),	/* krb5_err.et:krb5:KRB5KDC_ERR_PADATA_TYPE_NOSUPP */
	N_("KDC has no support for transited type"),	/* krb5_err.et:krb5:KRB5KDC_ERR_TRTYPE_NOSUPP */
	N_("Clients credentials have been revoked"),	/* krb5_err.et:krb5:KRB5KDC_ERR_CLIENT_REVOKED */
	N_("Credentials for server have been revoked"),	/* krb5_err.et:krb5:KRB5KDC_ERR_SERVICE_REVOKED */
	N_("TGT has been revoked"),	/* krb5_err.et:krb5:KRB5KDC_ERR_TGT_REVOKED */
	N_("Client not yet valid - try again later"),	/* krb5_err.et:krb5:KRB5KDC_ERR_CLIENT_NOTYET */
	N_("Server not yet valid - try again later"),	/* krb5_err.et:krb5:KRB5KDC_ERR_SERVICE_NOTYET */
	N_("Password has expired"),	/* krb5_err.et:krb5:KRB5KDC_ERR_KEY_EXP */
	N_("Preauthentication failed"),	/* krb5_err.et:krb5:KRB5KDC_ERR_PREAUTH_FAILED */
	N_("Additional pre-authentication required"),	/* krb5_err.et:krb5:KRB5KDC_ERR_PREAUTH_REQUIRED */
	N_("Requested server and ticket don't match"),	/* krb5_err.et:krb5:KRB5KDC_ERR_SERVER_NOMATCH */
	N_("Decrypt integrity check failed"),	/* krb5_err.et:krb5:KRB5KRB_AP_ERR_BAD_INTEGRITY */
	N_("Ticket expired"),	/* krb5_err.et:krb5:KRB5KRB_AP_ERR_TKT_EXPIRED */
	N_("Ticket not yet valid"),	/* krb5_err.et:krb5:KRB5KRB_AP_ERR_TKT_NYV */
	N_("Request is a replay"),	/* krb5_err.et:krb5:KRB5KRB_AP_ERR_REPEAT */
	N_("The ticket isn't for us"),	/* krb5_err.et:krb5:KRB5KRB_AP_ERR_NOT_US */
	N_("Ticket/authenticator don't match"),	/* krb5_err.et:krb5:KRB5KRB_AP_ERR_BADMATCH */
	N_("Clock skew too great"),	/* krb5_err.et:krb5:KRB5KRB_AP_ERR_SKEW */
	N_("Incorrect net address"),	/* krb5_err.et:krb5:KRB5KRB_AP_ERR_BADADDR */
	N_("Protocol version mismatch"),	/* krb5_err.et:krb5:KRB5KRB_AP_ERR_BADVERSION */
	N_("Invalid message type"),	/* krb5_err.et:krb5:KRB5KRB_AP_ERR_MSG_TYPE */
	N_("Message stream modified"),	/* krb5_err.et:krb5:KRB5KRB_AP_ERR_MODIFIED */
	N_("Message out of order"),	/* krb5_err.et:krb5:KRB5KRB_AP_ERR_BADORDER */
	N_("Illegal cross-realm ticket"),	/* krb5_err.et:krb5:KRB5KRB_AP_ERR_ILL_CR_TKT */
	N_("Key version is not available"),	/* krb5_err.et:krb5:KRB5KRB_AP_ERR_BADKEYVER */
	N_("Service key not available"),	/* krb5_err.et:krb5:KRB5KRB_AP_ERR_NOKEY */
	N_("Mutual authentication failed"),	/* krb5_err.et:krb5:KRB5KRB_AP_ERR_MUT_FAIL */
	N_("Incorrect message direction"),	/* krb5_err.et:krb5:KRB5KRB_AP_ERR_BADDIRECTION */
	N_("Alternative authentication method required"),	/* krb5_err.et:krb5:KRB5KRB_AP_ERR_METHOD */
	N_("Incorrect sequence number in message"),	/* krb5_err.et:krb5:KRB5KRB_AP_ERR_BADSEQ */
	N_("Inappropriate type of checksum in message"),	/* krb5_err.et:krb5:KRB5KRB_AP_ERR_INAPP_CKSUM */
	N_("Policy rejects transited path"),	/* krb5_err.et:krb5:KRB5KRB_AP_PATH_NOT_ACCEPTED */
	N_("Response too big for UDP, retry with TCP"),	/* krb5_err.et:krb5:KRB5KRB_ERR_RESPONSE_TOO_BIG */
	N_("Generic error (see e-text)"),	/* krb5_err.et:krb5:KRB5KRB_ERR_GENERIC */
	N_("Field is too long for this implementation"),	/* krb5_err.et:krb5:KRB5KRB_ERR_FIELD_TOOLONG */
	N_("Invalid flag for file lock mode"),	/* krb5_err.et:krb5:KRB5_LIBOS_BADLOCKFLAG */
	N_("Cannot read password"),	/* krb5_err.et:krb5:KRB5_LIBOS_CANTREADPWD */
	N_("Password mismatch"),	/* krb5_err.et:krb5:KRB5_LIBOS_BADPWDMATCH */
	N_("Password read interrupted"),	/* krb5_err.et:krb5:KRB5_LIBOS_PWDINTR */
	N_("Illegal character in component name"),	/* krb5_err.et:krb5:KRB5_PARSE_ILLCHAR */
	N_("Malformed representation of principal"),	/* krb5_err.et:krb5:KRB5_PARSE_MALFORMED */
	N_("Can't open/find Kerberos configuration file"),	/* krb5_err.et:krb5:KRB5_CONFIG_CANTOPEN */
	N_("Improper format of Kerberos configuration file"),	/* krb5_err.et:krb5:KRB5_CONFIG_BADFORMAT */
	N_("Insufficient space to return complete information"),	/* krb5_err.et:krb5:KRB5_CONFIG_NOTENUFSPACE */
	N_("Invalid message type specified for encoding"),	/* krb5_err.et:krb5:KRB5_BADMSGTYPE */
	N_("Credential cache name malformed"),	/* krb5_err.et:krb5:KRB5_CC_BADNAME */
	N_("Unknown credential cache type"),	/* krb5_err.et:krb5:KRB5_CC_UNKNOWN_TYPE */
	N_("Matching credential not found"),	/* krb5_err.et:krb5:KRB5_CC_NOTFOUND */
	N_("End of credential cache reached"),	/* krb5_err.et:krb5:KRB5_CC_END */
	N_("Request did not supply a ticket"),	/* krb5_err.et:krb5:KRB5_NO_TKT_SUPPLIED */
	N_("Wrong principal in request"),	/* krb5_err.et:krb5:KRB5KRB_AP_WRONG_PRINC */
	N_("Ticket has invalid flag set"),	/* krb5_err.et:krb5:KRB5KRB_AP_ERR_TKT_INVALID */
	N_("Requested principal and ticket don't match"),	/* krb5_err.et:krb5:KRB5_PRINC_NOMATCH */
	N_("KDC reply did not match expectations"),	/* krb5_err.et:krb5:KRB5_KDCREP_MODIFIED */
	N_("Clock skew too great in KDC reply"),	/* krb5_err.et:krb5:KRB5_KDCREP_SKEW */
	N_("Client/server realm mismatch in initial ticket request"),	/* krb5_err.et:krb5:KRB5_IN_TKT_REALM_MISMATCH */
	N_("Program lacks support for encryption type"),	/* krb5_err.et:krb5:KRB5_PROG_ETYPE_NOSUPP */
	N_("Program lacks support for key type"),	/* krb5_err.et:krb5:KRB5_PROG_KEYTYPE_NOSUPP */
	N_("Requested encryption type not used in message"),	/* krb5_err.et:krb5:KRB5_WRONG_ETYPE */
	N_("Program lacks support for checksum type"),	/* krb5_err.et:krb5:KRB5_PROG_SUMTYPE_NOSUPP */
	N_("Cannot find KDC for requested realm"),	/* krb5_err.et:krb5:KRB5_REALM_UNKNOWN */
	N_("Kerberos service unknown"),	/* krb5_err.et:krb5:KRB5_SERVICE_UNKNOWN */
	N_("Cannot contact any KDC for requested realm"),	/* krb5_err.et:krb5:KRB5_KDC_UNREACH */
	N_("No local name found for principal name"),	/* krb5_err.et:krb5:KRB5_NO_LOCALNAME */
	N_("Mutual authentication failed"),	/* krb5_err.et:krb5:KRB5_MUTUAL_FAILED */
	N_("Replay cache type is already registered"),	/* krb5_err.et:krb5:KRB5_RC_TYPE_EXISTS */
	N_("No more memory to allocate (in replay cache code)"),	/* krb5_err.et:krb5:KRB5_RC_MALLOC */
	N_("Replay cache type is unknown"),	/* krb5_err.et:krb5:KRB5_RC_TYPE_NOTFOUND */
	N_("Generic unknown RC error"),	/* krb5_err.et:krb5:KRB5_RC_UNKNOWN */
	N_("Message is a replay"),	/* krb5_err.et:krb5:KRB5_RC_REPLAY */
	N_("Replay I/O operation failed XXX"),	/* krb5_err.et:krb5:KRB5_RC_IO */
	N_("Replay cache type does not support non-volatile storage"),	/* krb5_err.et:krb5:KRB5_RC_NOIO */
	N_("Replay cache name parse/format error"),	/* krb5_err.et:krb5:KRB5_RC_PARSE */
	N_("End-of-file on replay cache I/O"),	/* krb5_err.et:krb5:KRB5_RC_IO_EOF */
	N_("No more memory to allocate (in replay cache I/O code)"),	/* krb5_err.et:krb5:KRB5_RC_IO_MALLOC */
	N_("Permission denied in replay cache code"),	/* krb5_err.et:krb5:KRB5_RC_IO_PERM */
	N_("I/O error in replay cache i/o code"),	/* krb5_err.et:krb5:KRB5_RC_IO_IO */
	N_("Generic unknown RC/IO error"),	/* krb5_err.et:krb5:KRB5_RC_IO_UNKNOWN */
	N_("Insufficient system space to store replay information"),	/* krb5_err.et:krb5:KRB5_RC_IO_SPACE */
	N_("Can't open/find realm translation file"),	/* krb5_err.et:krb5:KRB5_TRANS_CANTOPEN */
	N_("Improper format of realm translation file"),	/* krb5_err.et:krb5:KRB5_TRANS_BADFORMAT */
	N_("Can't open/find lname translation database"),	/* krb5_err.et:krb5:KRB5_LNAME_CANTOPEN */
	N_("No translation available for requested principal"),	/* krb5_err.et:krb5:KRB5_LNAME_NOTRANS */
	N_("Improper format of translation database entry"),	/* krb5_err.et:krb5:KRB5_LNAME_BADFORMAT */
	N_("Cryptosystem internal error"),	/* krb5_err.et:krb5:KRB5_CRYPTO_INTERNAL */
	N_("Key table name malformed"),	/* krb5_err.et:krb5:KRB5_KT_BADNAME */
	N_("Unknown Key table type"),	/* krb5_err.et:krb5:KRB5_KT_UNKNOWN_TYPE */
	N_("Key table entry not found"),	/* krb5_err.et:krb5:KRB5_KT_NOTFOUND */
	N_("End of key table reached"),	/* krb5_err.et:krb5:KRB5_KT_END */
	N_("Cannot write to specified key table"),	/* krb5_err.et:krb5:KRB5_KT_NOWRITE */
	N_("Error writing to key table"),	/* krb5_err.et:krb5:KRB5_KT_IOERR */
	N_("Cannot find ticket for requested realm"),	/* krb5_err.et:krb5:KRB5_NO_TKT_IN_RLM */
	N_("DES key has bad parity"),	/* krb5_err.et:krb5:KRB5DES_BAD_KEYPAR */
	N_("DES key is a weak key"),	/* krb5_err.et:krb5:KRB5DES_WEAK_KEY */
	N_("Bad encryption type"),	/* krb5_err.et:krb5:KRB5_BAD_ENCTYPE */
	N_("Key size is incompatible with encryption type"),	/* krb5_err.et:krb5:KRB5_BAD_KEYSIZE */
	N_("Message size is incompatible with encryption type"),	/* krb5_err.et:krb5:KRB5_BAD_MSIZE */
	N_("Credentials cache type is already registered."),	/* krb5_err.et:krb5:KRB5_CC_TYPE_EXISTS */
	N_("Key table type is already registered."),	/* krb5_err.et:krb5:KRB5_KT_TYPE_EXISTS */
	N_("Credentials cache I/O operation failed XXX"),	/* krb5_err.et:krb5:KRB5_CC_IO */
	N_("Credentials cache permissions incorrect"),	/* krb5_err.et:krb5:KRB5_FCC_PERM */
	N_("No credentials cache found"),	/* krb5_err.et:krb5:KRB5_FCC_NOFILE */
	N_("Internal credentials cache error"),	/* krb5_err.et:krb5:KRB5_FCC_INTERNAL */
	N_("Error writing to credentials cache"),	/* krb5_err.et:krb5:KRB5_CC_WRITE */
	N_("No more memory to allocate (in credentials cache code)"),	/* krb5_err.et:krb5:KRB5_CC_NOMEM */
	N_("Bad format in credentials cache"),	/* krb5_err.et:krb5:KRB5_CC_FORMAT */
	N_("No credentials found with supported encryption types"),	/* krb5_err.et:krb5:KRB5_CC_NOT_KTYPE */
	N_("Invalid KDC option combination (library internal error)"),	/* krb5_err.et:krb5:KRB5_INVALID_FLAGS */
	N_("Request missing second ticket"),	/* krb5_err.et:krb5:KRB5_NO_2ND_TKT */
	N_("No credentials supplied to library routine"),	/* krb5_err.et:krb5:KRB5_NOCREDS_SUPPLIED */
	N_("Bad sendauth version was sent"),	/* krb5_err.et:krb5:KRB5_SENDAUTH_BADAUTHVERS */
	N_("Bad application version was sent (via sendauth)"),	/* krb5_err.et:krb5:KRB5_SENDAUTH_BADAPPLVERS */
	N_("Bad response (during sendauth exchange)"),	/* krb5_err.et:krb5:KRB5_SENDAUTH_BADRESPONSE */
	N_("Server rejected authentication (during sendauth exchange)"),	/* krb5_err.et:krb5:KRB5_SENDAUTH_REJECTED */
	N_("Unsupported preauthentication type"),	/* krb5_err.et:krb5:KRB5_PREAUTH_BAD_TYPE */
	N_("Required preauthentication key not supplied"),	/* krb5_err.et:krb5:KRB5_PREAUTH_NO_KEY */
	N_("Generic preauthentication failure"),	/* krb5_err.et:krb5:KRB5_PREAUTH_FAILED */
	N_("Unsupported replay cache format version number"),	/* krb5_err.et:krb5:KRB5_RCACHE_BADVNO */
	N_("Unsupported credentials cache format version number"),	/* krb5_err.et:krb5:KRB5_CCACHE_BADVNO */
	N_("Unsupported key table format version number"),	/* krb5_err.et:krb5:KRB5_KEYTAB_BADVNO */
	N_("Program lacks support for address type"),	/* krb5_err.et:krb5:KRB5_PROG_ATYPE_NOSUPP */
	N_("Message replay detection requires rcache parameter"),	/* krb5_err.et:krb5:KRB5_RC_REQUIRED */
	N_("Hostname cannot be canonicalized"),	/* krb5_err.et:krb5:KRB5_ERR_BAD_HOSTNAME */
	N_("Cannot determine realm for host"),	/* krb5_err.et:krb5:KRB5_ERR_HOST_REALM_UNKNOWN */
	N_("Conversion to service principal undefined for name type"),	/* krb5_err.et:krb5:KRB5_SNAME_UNSUPP_NAMETYPE */
	N_("Initial Ticket response appears to be Version 4 error"),	/* krb5_err.et:krb5:KRB5KRB_AP_ERR_V4_REPLY */
	N_("Cannot resolve network address for KDC in requested realm"),	/* krb5_err.et:krb5:KRB5_REALM_CANT_RESOLVE */
	N_("Requesting ticket can't get forwardable tickets"),	/* krb5_err.et:krb5:KRB5_TKT_NOT_FORWARDABLE */
	N_("Bad principal name while trying to forward credentials"),	/* krb5_err.et:krb5:KRB5_FWD_BAD_PRINCIPAL */
	N_("Looping detected inside krb5_get_in_tkt"),	/* krb5_err.et:krb5:KRB5_GET_IN_TKT_LOOP */
	N_("Configuration file does not specify default realm"),	/* krb5_err.et:krb5:KRB5_CONFIG_NODEFREALM */
	N_("Bad SAM flags in obtain_sam_padata"),	/* krb5_err.et:krb5:KRB5_SAM_UNSUPPORTED */
	N_("Invalid encryption type in SAM challenge"),	/* krb5_err.et:krb5:KRB5_SAM_INVALID_ETYPE */
	N_("Missing checksum in SAM challenge"),	/* krb5_err.et:krb5:KRB5_SAM_NO_CHECKSUM */
	N_("Bad checksum in SAM challenge"),	/* krb5_err.et:krb5:KRB5_SAM_BAD_CHECKSUM */
	N_("Keytab name too long"),	/* krb5_err.et:krb5:KRB5_KT_NAME_TOOLONG */
	N_("Key version number for principal in key table is incorrect"),	/* krb5_err.et:krb5:KRB5_KT_KVNONOTFOUND */
	N_("This application has expired"),	/* krb5_err.et:krb5:KRB5_APPL_EXPIRED */
	N_("This Krb5 library has expired"),	/* krb5_err.et:krb5:KRB5_LIB_EXPIRED */
	N_("New password cannot be zero length"),	/* krb5_err.et:krb5:KRB5_CHPW_PWDNULL */
	N_("Password change failed"),	/* krb5_err.et:krb5:KRB5_CHPW_FAIL */
	N_("Bad format in keytab"),	/* krb5_err.et:krb5:KRB5_KT_FORMAT */
	N_("Encryption type not permitted"),	/* krb5_err.et:krb5:KRB5_NOPERM_ETYPE */
	N_("No supported encryption types (config file error?)"),	/* krb5_err.et:krb5:KRB5_CONFIG_ETYPE_NOSUPP */
	N_("Program called an obsolete, deleted function"),	/* krb5_err.et:krb5:KRB5_OBSOLETE_FN */
	N_("unknown getaddrinfo failure"),	/* krb5_err.et:krb5:KRB5_EAI_FAIL */
	N_("no data available for host/domain name"),	/* krb5_err.et:krb5:KRB5_EAI_NODATA */
	N_("host/domain name not found"),	/* krb5_err.et:krb5:KRB5_EAI_NONAME */
	N_("service name unknown"),	/* krb5_err.et:krb5:KRB5_EAI_SERVICE */
	N_("Cannot determine realm for numeric host address"),	/* krb5_err.et:krb5:KRB5_ERR_NUMERIC_REALM */
	N_("Invalid key generation parameters from KDC"),	/* krb5_err.et:krb5:KRB5_ERR_BAD_S2K_PARAMS */
	N_("service not available"),	/* krb5_err.et:krb5:KRB5_ERR_NO_SERVICE */
	N_("Ccache function not supported: read-only ccache type"),	/* krb5_err.et:krb5:KRB5_CC_READONLY */
	N_("Ccache function not supported: not implemented"),	/* krb5_err.et:krb5:KRB5_CC_NOSUPP */
	N_("ASN.1 failed call to system time library"),	/* asn1_err.et:asn1:ASN1_BAD_TIMEFORMAT */
	N_("ASN.1 structure is missing a required field"),	/* asn1_err.et:asn1:ASN1_MISSING_FIELD */
	N_("ASN.1 unexpected field number"),	/* asn1_err.et:asn1:ASN1_MISPLACED_FIELD */
	N_("ASN.1 type numbers are inconsistent"),	/* asn1_err.et:asn1:ASN1_TYPE_MISMATCH */
	N_("ASN.1 value too large"),	/* asn1_err.et:asn1:ASN1_OVERFLOW */
	N_("ASN.1 encoding ended unexpectedly"),	/* asn1_err.et:asn1:ASN1_OVERRUN */
	N_("ASN.1 identifier doesn't match expected value"),	/* asn1_err.et:asn1:ASN1_BAD_ID */
	N_("ASN.1 length doesn't match expected value"),	/* asn1_err.et:asn1:ASN1_BAD_LENGTH */
	N_("ASN.1 badly-formatted encoding"),	/* asn1_err.et:asn1:ASN1_BAD_FORMAT */
	N_("ASN.1 parse error"),	/* asn1_err.et:asn1:ASN1_PARSE_ERROR */
	N_("ASN.1 bad return from gmtime"),	/* asn1_err.et:asn1:ASN1_BAD_GMTIME */
	N_("ASN.1 non-constructed indefinite encoding"),	/* asn1_err.et:asn1:ASN1_MISMATCH_INDEF */
	N_("ASN.1 missing expected EOC"),	/* asn1_err.et:asn1:ASN1_MISSING_EOC */
	N_("Kerberos V5 magic number table"),	/* kv5m_err.et:kv5m:KV5M_NONE */
	N_("Bad magic number for krb5_principal structure"),	/* kv5m_err.et:kv5m:KV5M_PRINCIPAL */
	N_("Bad magic number for krb5_data structure"),	/* kv5m_err.et:kv5m:KV5M_DATA */
	N_("Bad magic number for krb5_keyblock structure"),	/* kv5m_err.et:kv5m:KV5M_KEYBLOCK */
	N_("Bad magic number for krb5_checksum structure"),	/* kv5m_err.et:kv5m:KV5M_CHECKSUM */
	N_("Bad magic number for krb5_encrypt_block structure"),	/* kv5m_err.et:kv5m:KV5M_ENCRYPT_BLOCK */
	N_("Bad magic number for krb5_enc_data structure"),	/* kv5m_err.et:kv5m:KV5M_ENC_DATA */
	N_("Bad magic number for krb5_cryptosystem_entry structure"),	/* kv5m_err.et:kv5m:KV5M_CRYPTOSYSTEM_ENTRY */
	N_("Bad magic number for krb5_cs_table_entry structure"),	/* kv5m_err.et:kv5m:KV5M_CS_TABLE_ENTRY */
	N_("Bad magic number for krb5_checksum_entry structure"),	/* kv5m_err.et:kv5m:KV5M_CHECKSUM_ENTRY */
	N_("Bad magic number for krb5_authdata structure"),	/* kv5m_err.et:kv5m:KV5M_AUTHDATA */
	N_("Bad magic number for krb5_transited structure"),	/* kv5m_err.et:kv5m:KV5M_TRANSITED */
	N_("Bad magic number for krb5_enc_tkt_part structure"),	/* kv5m_err.et:kv5m:KV5M_ENC_TKT_PART */
	N_("Bad magic number for krb5_ticket structure"),	/* kv5m_err.et:kv5m:KV5M_TICKET */
	N_("Bad magic number for krb5_authenticator structure"),	/* kv5m_err.et:kv5m:KV5M_AUTHENTICATOR */
	N_("Bad magic number for krb5_tkt_authent structure"),	/* kv5m_err.et:kv5m:KV5M_TKT_AUTHENT */
	N_("Bad magic number for krb5_creds structure"),	/* kv5m_err.et:kv5m:KV5M_CREDS */
	N_("Bad magic number for krb5_last_req_entry structure"),	/* kv5m_err.et:kv5m:KV5M_LAST_REQ_ENTRY */
	N_("Bad magic number for krb5_pa_data structure"),	/* kv5m_err.et:kv5m:KV5M_PA_DATA */
	N_("Bad magic number for krb5_kdc_req structure"),	/* kv5m_err.et:kv5m:KV5M_KDC_REQ */
	N_("Bad magic number for krb5_enc_kdc_rep_part structure"),	/* kv5m_err.et:kv5m:KV5M_ENC_KDC_REP_PART */
	N_("Bad magic number for krb5_kdc_rep structure"),	/* kv5m_err.et:kv5m:KV5M_KDC_REP */
	N_("Bad magic number for krb5_error structure"),	/* kv5m_err.et:kv5m:KV5M_ERROR */
	N_("Bad magic number for krb5_ap_req structure"),	/* kv5m_err.et:kv5m:KV5M_AP_REQ */
	N_("Bad magic number for krb5_ap_rep structure"),	/* kv5m_err.et:kv5m:KV5M_AP_REP */
	N_("Bad magic number for krb5_ap_rep_enc_part structure"),	/* kv5m_err.et:kv5m:KV5M_AP_REP_ENC_PART */
	N_("Bad magic number for krb5_response structure"),	/* kv5m_err.et:kv5m:KV5M_RESPONSE */
	N_("Bad magic number for krb5_safe structure"),	/* kv5m_err.et:kv5m:KV5M_SAFE */
	N_("Bad magic number for krb5_priv structure"),	/* kv5m_err.et:kv5m:KV5M_PRIV */
	N_("Bad magic number for krb5_priv_enc_part structure"),	/* kv5m_err.et:kv5m:KV5M_PRIV_ENC_PART */
	N_("Bad magic number for krb5_cred structure"),	/* kv5m_err.et:kv5m:KV5M_CRED */
	N_("Bad magic number for krb5_cred_info structure"),	/* kv5m_err.et:kv5m:KV5M_CRED_INFO */
	N_("Bad magic number for krb5_cred_enc_part structure"),	/* kv5m_err.et:kv5m:KV5M_CRED_ENC_PART */
	N_("Bad magic number for krb5_pwd_data structure"),	/* kv5m_err.et:kv5m:KV5M_PWD_DATA */
	N_("Bad magic number for krb5_address structure"),	/* kv5m_err.et:kv5m:KV5M_ADDRESS */
	N_("Bad magic number for krb5_keytab_entry structure"),	/* kv5m_err.et:kv5m:KV5M_KEYTAB_ENTRY */
	N_("Bad magic number for krb5_context structure"),	/* kv5m_err.et:kv5m:KV5M_CONTEXT */
	N_("Bad magic number for krb5_os_context structure"),	/* kv5m_err.et:kv5m:KV5M_OS_CONTEXT */
	N_("Bad magic number for krb5_alt_method structure"),	/* kv5m_err.et:kv5m:KV5M_ALT_METHOD */
	N_("Bad magic number for krb5_etype_info_entry structure"),	/* kv5m_err.et:kv5m:KV5M_ETYPE_INFO_ENTRY */
	N_("Bad magic number for krb5_db_context structure"),	/* kv5m_err.et:kv5m:KV5M_DB_CONTEXT */
	N_("Bad magic number for krb5_auth_context structure"),	/* kv5m_err.et:kv5m:KV5M_AUTH_CONTEXT */
	N_("Bad magic number for krb5_keytab structure"),	/* kv5m_err.et:kv5m:KV5M_KEYTAB */
	N_("Bad magic number for krb5_rcache structure"),	/* kv5m_err.et:kv5m:KV5M_RCACHE */
	N_("Bad magic number for krb5_ccache structure"),	/* kv5m_err.et:kv5m:KV5M_CCACHE */
	N_("Bad magic number for krb5_preauth_ops"),	/* kv5m_err.et:kv5m:KV5M_PREAUTH_OPS */
	N_("Bad magic number for krb5_sam_challenge"),	/* kv5m_err.et:kv5m:KV5M_SAM_CHALLENGE */
	N_("Bad magic number for krb5_sam_challenge_2"),	/* kv5m_err.et:kv5m:KV5M_SAM_CHALLENGE_2 */
	N_("Bad magic number for krb5_sam_key"),	/* kv5m_err.et:kv5m:KV5M_SAM_KEY */
	N_("Bad magic number for krb5_enc_sam_response_enc"),	/* kv5m_err.et:kv5m:KV5M_ENC_SAM_RESPONSE_ENC */
	N_("Bad magic number for krb5_enc_sam_response_enc"),	/* kv5m_err.et:kv5m:KV5M_ENC_SAM_RESPONSE_ENC_2 */
	N_("Bad magic number for krb5_sam_response"),	/* kv5m_err.et:kv5m:KV5M_SAM_RESPONSE */
	N_("Bad magic number for krb5_sam_response 2"),	/* kv5m_err.et:kv5m:KV5M_SAM_RESPONSE_2 */
	N_("Bad magic number for krb5_predicted_sam_response"),	/* kv5m_err.et:kv5m:KV5M_PREDICTED_SAM_RESPONSE */
	N_("Bad magic number for passwd_phrase_element"),	/* kv5m_err.et:kv5m:KV5M_PASSWD_PHRASE_ELEMENT */
	N_("Bad magic number for GSSAPI OID"),	/* kv5m_err.et:kv5m:KV5M_GSS_OID */
	N_("Bad magic number for GSSAPI QUEUE"),	/* kv5m_err.et:kv5m:KV5M_GSS_QUEUE */
	N_("$Id$"),	/* kdb5_err.et:kdb5:KRB5_KDB_RCSID */
	N_("Entry already exists in database"),	/* kdb5_err.et:kdb5:KRB5_KDB_INUSE */
	N_("Database store error"),	/* kdb5_err.et:kdb5:KRB5_KDB_UK_SERROR */
	N_("Database read error"),	/* kdb5_err.et:kdb5:KRB5_KDB_UK_RERROR */
	N_("Insufficient access to perform requested operation"),	/* kdb5_err.et:kdb5:KRB5_KDB_UNAUTH */
	N_("No such entry in the database"),	/* kdb5_err.et:kdb5:KRB5_KDB_NOENTRY */
	N_("Illegal use of wildcard"),	/* kdb5_err.et:kdb5:KRB5_KDB_ILL_WILDCARD */
	N_("Database is locked or in use--try again later"),	/* kdb5_err.et:kdb5:KRB5_KDB_DB_INUSE */
	N_("Database was modified during read"),	/* kdb5_err.et:kdb5:KRB5_KDB_DB_CHANGED */
	N_("Database record is incomplete or corrupted"),	/* kdb5_err.et:kdb5:KRB5_KDB_TRUNCATED_RECORD */
	N_("Attempt to lock database twice"),	/* kdb5_err.et:kdb5:KRB5_KDB_RECURSIVELOCK */
	N_("Attempt to unlock database when not locked"),	/* kdb5_err.et:kdb5:KRB5_KDB_NOTLOCKED */
	N_("Invalid kdb lock mode"),	/* kdb5_err.et:kdb5:KRB5_KDB_BADLOCKMODE */
	N_("Database has not been initialized"),	/* kdb5_err.et:kdb5:KRB5_KDB_DBNOTINITED */
	N_("Database has already been initialized"),	/* kdb5_err.et:kdb5:KRB5_KDB_DBINITED */
	N_("Bad direction for converting keys"),	/* kdb5_err.et:kdb5:KRB5_KDB_ILLDIRECTION */
	N_("Cannot find master key record in database"),	/* kdb5_err.et:kdb5:KRB5_KDB_NOMASTERKEY */
	N_("Master key does not match database"),	/* kdb5_err.et:kdb5:KRB5_KDB_BADMASTERKEY */
	N_("Key size in database is invalid"),	/* kdb5_err.et:kdb5:KRB5_KDB_INVALIDKEYSIZE */
	N_("Cannot find/read stored master key"),	/* kdb5_err.et:kdb5:KRB5_KDB_CANTREAD_STORED */
	N_("Stored master key is corrupted"),	/* kdb5_err.et:kdb5:KRB5_KDB_BADSTORED_MKEY */
	N_("Insufficient access to lock database"),	/* kdb5_err.et:kdb5:KRB5_KDB_CANTLOCK_DB */
	N_("Database format error"),	/* kdb5_err.et:kdb5:KRB5_KDB_DB_CORRUPT */
	N_("Unsupported version in database entry"),	/* kdb5_err.et:kdb5:KRB5_KDB_BAD_VERSION */
	N_("Unsupported salt type"),	/* kdb5_err.et:kdb5:KRB5_KDB_BAD_SALTTYPE */
	N_("Unsupported encryption type"),	/* kdb5_err.et:kdb5:KRB5_KDB_BAD_ENCTYPE */
	N_("Bad database creation flags"),	/* kdb5_err.et:kdb5:KRB5_KDB_BAD_CREATEFLAGS */
	N_("No matching key in entry having a permitted enctype"),	/* kdb5_err.et:kdb5:KRB5_KDB_NO_PERMITTED_KEY */
	N_("No matching key in entry"),	/* kdb5_err.et:kdb5:KRB5_KDB_NO_MATCHING_KEY */
	N_("No Error"),	/* adb_err.et:adb:OSA_ADB_NOERR */
	N_("Principal or policy already exists"),	/* adb_err.et:adb:OSA_ADB_DUP */
	N_("Principal or policy does not exist"),	/* adb_err.et:adb:OSA_ADB_NOENT */
	N_("Database not initialized"),	/* adb_err.et:adb:OSA_ADB_DBINIT */
	N_("Invalid policy name"),	/* adb_err.et:adb:OSA_ADB_BAD_POLICY */
	N_("Invalid principal name"),	/* adb_err.et:adb:OSA_ADB_BAD_PRINC */
	N_("Database inconsistency detected"),	/* adb_err.et:adb:OSA_ADB_BAD_DB */
	N_("XDR encoding error"),	/* adb_err.et:adb:OSA_ADB_XDR_FAILURE */
	N_("Failure!"),	/* adb_err.et:adb:OSA_ADB_FAILURE */
	N_("Bad lock mode"),	/* adb_err.et:adb:OSA_ADB_BADLOCKMODE */
	N_("Cannot lock database"),	/* adb_err.et:adb:OSA_ADB_CANTLOCK_DB */
	N_("Database not locked"),	/* adb_err.et:adb:OSA_ADB_NOTLOCKED */
	N_("KADM5 administration database lock file missing"),	/* adb_err.et:adb:OSA_ADB_NOLOCKFILE */
	N_("Insufficient permission to lock file"),	/* adb_err.et:adb:OSA_ADB_NOEXCL_PERM */
	N_("Operation failed for unspecified reason"),	/* kadm_err.et:ovk:KADM5_FAILURE */
	N_("Operation requires ``get'' privilege"),	/* kadm_err.et:ovk:KADM5_AUTH_GET */
	N_("Operation requires ``add'' privilege"),	/* kadm_err.et:ovk:KADM5_AUTH_ADD */
	N_("Operation requires ``modify'' privilege"),	/* kadm_err.et:ovk:KADM5_AUTH_MODIFY */
	N_("Operation requires ``delete'' privilege"),	/* kadm_err.et:ovk:KADM5_AUTH_DELETE */
	N_("Insufficient authorization for operation"),	/* kadm_err.et:ovk:KADM5_AUTH_INSUFFICIENT */
	N_("Database inconsistency detected"),	/* kadm_err.et:ovk:KADM5_BAD_DB */
	N_("Principal or policy already exists"),	/* kadm_err.et:ovk:KADM5_DUP */
	N_("Communication failure with server"),	/* kadm_err.et:ovk:KADM5_RPC_ERROR */
	N_("No administration server found for realm"),	/* kadm_err.et:ovk:KADM5_NO_SRV */
	N_("Password history principal key version mismatch"),	/* kadm_err.et:ovk:KADM5_BAD_HIST_KEY */
	N_("Connection to server not initialized"),	/* kadm_err.et:ovk:KADM5_NOT_INIT */
	N_("Principal does not exist"),	/* kadm_err.et:ovk:KADM5_UNK_PRINC */
	N_("Policy does not exist"),	/* kadm_err.et:ovk:KADM5_UNK_POLICY */
	N_("Invalid field mask for operation"),	/* kadm_err.et:ovk:KADM5_BAD_MASK */
	N_("Invalid number of character classes"),	/* kadm_err.et:ovk:KADM5_BAD_CLASS */
	N_("Invalid password length"),	/* kadm_err.et:ovk:KADM5_BAD_LENGTH */
	N_("Illegal policy name"),	/* kadm_err.et:ovk:KADM5_BAD_POLICY */
	N_("Illegal principal name"),	/* kadm_err.et:ovk:KADM5_BAD_PRINCIPAL */
	N_("Invalid auxillary attributes"),	/* kadm_err.et:ovk:KADM5_BAD_AUX_ATTR */
	N_("Invalid password history count"),	/* kadm_err.et:ovk:KADM5_BAD_HISTORY */
	N_("Password minimum life is greater than password maximum life"),	/* kadm_err.et:ovk:KADM5_BAD_MIN_PASS_LIFE */
	N_("Password is too short"),	/* kadm_err.et:ovk:KADM5_PASS_Q_TOOSHORT */
	N_("Password does not contain enough character classes"),	/* kadm_err.et:ovk:KADM5_PASS_Q_CLASS */
	N_("Password is in the password dictionary"),	/* kadm_err.et:ovk:KADM5_PASS_Q_DICT */
	N_("Cannot reuse password"),	/* kadm_err.et:ovk:KADM5_PASS_REUSE */
	N_("Current password's minimum life has not expired"),	/* kadm_err.et:ovk:KADM5_PASS_TOOSOON */
	N_("Policy is in use"),	/* kadm_err.et:ovk:KADM5_POLICY_REF */
	N_("Connection to server already initialized"),	/* kadm_err.et:ovk:KADM5_INIT */
	N_("Incorrect password"),	/* kadm_err.et:ovk:KADM5_BAD_PASSWORD */
	N_("Cannot change protected principal"),	/* kadm_err.et:ovk:KADM5_PROTECT_PRINCIPAL */
	N_("Programmer error!  Bad Admin server handle"),	/* kadm_err.et:ovk:KADM5_BAD_SERVER_HANDLE */
	N_("Programmer error!  Bad API structure version"),	/* kadm_err.et:ovk:KADM5_BAD_STRUCT_VERSION */
	N_("API structure version specified by application is no longer supported (to fix, recompile application against current KADM5 API header files and libraries)"),	/* kadm_err.et:ovk:KADM5_OLD_STRUCT_VERSION */
	N_("API structure version specified by application is unknown to libraries (to fix, obtain current KADM5 API header files and libraries and recompile application)"),	/* kadm_err.et:ovk:KADM5_NEW_STRUCT_VERSION */
	N_("Programmer error!  Bad API version"),	/* kadm_err.et:ovk:KADM5_BAD_API_VERSION */
	N_("API version specified by application is no longer supported by libraries (to fix, update application to adhere to current API version and recompile)"),	/* kadm_err.et:ovk:KADM5_OLD_LIB_API_VERSION */
	N_("API version specified by application is no longer supported by server (to fix, update application to adhere to current API version and recompile)"),	/* kadm_err.et:ovk:KADM5_OLD_SERVER_API_VERSION */
	N_("API version specified by application is unknown to libraries (to fix, obtain current KADM5 API header files and libraries and recompile application)"),	/* kadm_err.et:ovk:KADM5_NEW_LIB_API_VERSION */
	N_("API version specified by application is unknown to server (to fix, obtain and install newest KADM5 Admin Server)"),	/* kadm_err.et:ovk:KADM5_NEW_SERVER_API_VERSION */
	N_("Database error! Required KADM5 principal missing"),	/* kadm_err.et:ovk:KADM5_SECURE_PRINC_MISSING */
	N_("The salt type of the specified principal does not support renaming"),	/* kadm_err.et:ovk:KADM5_NO_RENAME_SALT */
	N_("Illegal configuration parameter for remote KADM5 client"),	/* kadm_err.et:ovk:KADM5_BAD_CLIENT_PARAMS */
	N_("Illegal configuration parameter for local KADM5 client"),	/* kadm_err.et:ovk:KADM5_BAD_SERVER_PARAMS */
	N_("Operation requires ``list'' privilege"),	/* kadm_err.et:ovk:KADM5_AUTH_LIST */
	N_("Operation requires ``change-password'' privilege"),	/* kadm_err.et:ovk:KADM5_AUTH_CHANGEPW */
	N_("GSS-API (or Kerberos) error"),	/* kadm_err.et:ovk:KADM5_GSS_ERROR */
	N_("Programmer error!  Illegal tagged data list type"),	/* kadm_err.et:ovk:KADM5_BAD_TL_TYPE */
	N_("Required parameters in kdc.conf missing"),	/* kadm_err.et:ovk:KADM5_MISSING_CONF_PARAMS */
	N_("Bad krb5 admin server hostname"),	/* kadm_err.et:ovk:KADM5_BAD_SERVER_NAME */
	N_("Operation requires ``set-key'' privilege"),	/* kadm_err.et:ovk:KADM5_AUTH_SETKEY */
	N_("Multiple values for single or folded enctype"),	/* kadm_err.et:ovk:KADM5_SETKEY_DUP_ENCTYPES */
	N_("Invalid enctype for setv4key"),	/* kadm_err.et:ovk:KADM5_SETV4KEY_INVAL_ENCTYPE */
	N_("Mismatched enctypes for setkey3"),	/* kadm_err.et:ovk:KADM5_SETKEY3_ETYPE_MISMATCH */
	N_("Missing parameters in krb5.conf required for kadmin client"),	/* kadm_err.et:ovk:KADM5_MISSING_KRB5_CONF_PARAMS */
	N_("while getting policy info."),	/* chpass_util_strings.et:ovku:CHPASS_UTIL_GET_POLICY_INFO */
	N_("while getting principal info."),	/* chpass_util_strings.et:ovku:CHPASS_UTIL_GET_PRINC_INFO */
	N_("New passwords do not match - password not changed.\n"),	/* chpass_util_strings.et:ovku:CHPASS_UTIL_NEW_PASSWORD_MISMATCH */
	N_("New password"),	/* chpass_util_strings.et:ovku:CHPASS_UTIL_NEW_PASSWORD_PROMPT */
	N_("New password (again)"),	/* chpass_util_strings.et:ovku:CHPASS_UTIL_NEW_PASSWORD_AGAIN_PROMPT */
	N_("You must type a password. Passwords must be at least one character long.\n"),	/* chpass_util_strings.et:ovku:CHPASS_UTIL_NO_PASSWORD_READ */
	N_("yet no policy set!  Contact your system security administrator."),	/* chpass_util_strings.et:ovku:CHPASS_UTIL_NO_POLICY_YET_Q_ERROR */
	N_("Password changed.\n"),	/* chpass_util_strings.et:ovku:CHPASS_UTIL_PASSWORD_CHANGED */
	N_("New password was found in a dictionary of possible passwords and\n\
therefore may be easily guessed. Please choose another password.\n\
See the ovpasswd man page for help in choosing a good password."),	/* chpass_util_strings.et:ovku:CHPASS_UTIL_PASSWORD_IN_DICTIONARY */
	N_("Password not changed."),	/* chpass_util_strings.et:ovku:CHPASS_UTIL_PASSWORD_NOT_CHANGED */
	N_("New password is too short.\n\
Please choose a password which is at least %d characters long."),	/* chpass_util_strings.et:ovku:CHPASS_UTIL_PASSWORD_TOO_SHORT */
	N_("New password does not have enough character classes.\n\
The character classes are:\n\
	- lower-case letters,\n\
	- upper-case letters,\n\
	- digits,\n\
	- punctuation, and\n\
	- all other characters (e.g., control characters).\n\
Please choose a password with at least %d character classes."),	/* chpass_util_strings.et:ovku:CHPASS_UTIL_TOO_FEW_CLASSES */
	N_("Password cannot be changed because it was changed too recently.\n\
Please wait until %s before you change it.\n\
If you need to change your password before then, contact your system\n\
security administrator."),	/* chpass_util_strings.et:ovku:CHPASS_UTIL_PASSWORD_TOO_SOON */
	N_("New password was used previously. Please choose a different password."),	/* chpass_util_strings.et:ovku:CHPASS_UTIL_PASSWORD_REUSE */
	N_("while trying to change password."),	/* chpass_util_strings.et:ovku:CHPASS_UTIL_WHILE_TRYING_TO_CHANGE */
	N_("while reading new password."),	/* chpass_util_strings.et:ovku:CHPASS_UTIL_WHILE_READING_PASSWORD */
	N_("$Header$"),	/* kadm_err.et:kadm:KADM_RCSID */
	N_("Cannot fetch local realm"),	/* kadm_err.et:kadm:KADM_NO_REALM */
	N_("Unable to fetch credentials"),	/* kadm_err.et:kadm:KADM_NO_CRED */
	N_("Bad key supplied"),	/* kadm_err.et:kadm:KADM_BAD_KEY */
	N_("Can't encrypt data"),	/* kadm_err.et:kadm:KADM_NO_ENCRYPT */
	N_("Cannot encode/decode authentication info"),	/* kadm_err.et:kadm:KADM_NO_AUTH */
	N_("Principal attemping change is in wrong realm"),	/* kadm_err.et:kadm:KADM_WRONG_REALM */
	N_("Packet is too large"),	/* kadm_err.et:kadm:KADM_NO_ROOM */
	N_("Version number is incorrect"),	/* kadm_err.et:kadm:KADM_BAD_VER */
	N_("Checksum does not match"),	/* kadm_err.et:kadm:KADM_BAD_CHK */
	N_("Unsealing private data failed"),	/* kadm_err.et:kadm:KADM_NO_READ */
	N_("Unsupported operation"),	/* kadm_err.et:kadm:KADM_NO_OPCODE */
	N_("Could not find administrating host"),	/* kadm_err.et:kadm:KADM_NO_HOST */
	N_("Administrating host name is unknown"),	/* kadm_err.et:kadm:KADM_UNK_HOST */
	N_("Could not find service name in services database"),	/* kadm_err.et:kadm:KADM_NO_SERV */
	N_("Could not create socket"),	/* kadm_err.et:kadm:KADM_NO_SOCK */
	N_("Could not connect to server"),	/* kadm_err.et:kadm:KADM_NO_CONN */
	N_("Could not fetch local socket address"),	/* kadm_err.et:kadm:KADM_NO_HERE */
	N_("Could not fetch master key"),	/* kadm_err.et:kadm:KADM_NO_MAST */
	N_("Could not verify master key"),	/* kadm_err.et:kadm:KADM_NO_VERI */
	N_("Entry already exists in database"),	/* kadm_err.et:kadm:KADM_INUSE */
	N_("Database store error"),	/* kadm_err.et:kadm:KADM_UK_SERROR */
	N_("Database read error"),	/* kadm_err.et:kadm:KADM_UK_RERROR */
	N_("Insufficient access to perform requested operation"),	/* kadm_err.et:kadm:KADM_UNAUTH */
	N_("Data is available for return to client"),	/* kadm_err.et:kadm:KADM_DATA */
	N_("No such entry in the database"),	/* kadm_err.et:kadm:KADM_NOENTRY */
	N_("Memory exhausted"),	/* kadm_err.et:kadm:KADM_NOMEM */
	N_("Could not fetch system hostname"),	/* kadm_err.et:kadm:KADM_NO_HOSTNAME */
	N_("Could not bind port"),	/* kadm_err.et:kadm:KADM_NO_BIND */
	N_("Length mismatch problem"),	/* kadm_err.et:kadm:KADM_LENGTH_ERROR */
	N_("Illegal use of wildcard"),	/* kadm_err.et:kadm:KADM_ILL_WILDCARD */
	N_("Database locked or in use"),	/* kadm_err.et:kadm:KADM_DB_INUSE */
	N_("Insecure password rejected"),	/* kadm_err.et:kadm:KADM_INSECURE_PW */
	N_("Cleartext password and DES key did not match"),	/* kadm_err.et:kadm:KADM_PW_MISMATCH */
	N_("Invalid principal for change srvtab request"),	/* kadm_err.et:kadm:KADM_NOT_SERV_PRINC */
	N_("Realm name too long"),	/* kadm_err.et:kadm:KADM_REALM_TOO_LONG */
	N_("Kerberos successful"),	/* krb_err.et:krb:KRBET_KSUCCESS */
	N_("Kerberos principal expired"),	/* krb_err.et:krb:KRBET_KDC_NAME_EXP */
	N_("Kerberos service expired"),	/* krb_err.et:krb:KRBET_KDC_SERVICE_EXP */
	N_("Kerberos auth expired"),	/* krb_err.et:krb:KRBET_KDC_AUTH_EXP */
	N_("Unknown kerberos protocol version"),	/* krb_err.et:krb:KRBET_KDC_PKT_VER */
	N_("Incorrect kerberos master key version for principal"),	/* krb_err.et:krb:KRBET_KDC_P_MKEY_VER */
	N_("Incorrect kerberos master key version for service"),	/* krb_err.et:krb:KRBET_KDC_S_MKEY_VER */
	N_("Bad byte order (kerberos)"),	/* krb_err.et:krb:KRBET_KDC_BYTE_ORDER */
	N_("Kerberos principal unknown"),	/* krb_err.et:krb:KRBET_KDC_PR_UNKNOWN */
	N_("Kerberos principal not unique"),	/* krb_err.et:krb:KRBET_KDC_PR_N_UNIQUE */
	N_("Kerberos principal has null key"),	/* krb_err.et:krb:KRBET_KDC_NULL_KEY */
	N_("Reserved error message 11 (kerberos)"),	/* krb_err.et:krb:KRBET_KRB_RES11 */
	N_("Reserved error message 12 (kerberos)"),	/* krb_err.et:krb:KRBET_KRB_RES12 */
	N_("Reserved error message 13 (kerberos)"),	/* krb_err.et:krb:KRBET_KRB_RES13 */
	N_("Reserved error message 14 (kerberos)"),	/* krb_err.et:krb:KRBET_KRB_RES14 */
	N_("Reserved error message 15 (kerberos)"),	/* krb_err.et:krb:KRBET_KRB_RES15 */
	N_("Reserved error message 16 (kerberos)"),	/* krb_err.et:krb:KRBET_KRB_RES16 */
	N_("Reserved error message 17 (kerberos)"),	/* krb_err.et:krb:KRBET_KRB_RES17 */
	N_("Reserved error message 18 (kerberos)"),	/* krb_err.et:krb:KRBET_KRB_RES18 */
	N_("Reserved error message 19 (kerberos)"),	/* krb_err.et:krb:KRBET_KRB_RES19 */
	N_("Generic error from Kerberos KDC"),	/* krb_err.et:krb:KRBET_KDC_GEN_ERR */
	N_("Can't read Kerberos ticket file"),	/* krb_err.et:krb:KRBET_GC_TKFIL */
	N_("Can't find Kerberos ticket or TGT"),	/* krb_err.et:krb:KRBET_GC_NOTKT */
	N_("Reserved error message 23 (krb_get_cred)"),	/* krb_err.et:krb:KRBET_KRB_RES23 */
	N_("Reserved error message 24 (krb_get_cred)"),	/* krb_err.et:krb:KRBET_KRB_RES24 */
	N_("Reserved error message 25 (krb_get_cred)"),	/* krb_err.et:krb:KRBET_KRB_RES25 */
	N_("Kerberos TGT Expired"),	/* krb_err.et:krb:KRBET_MK_AP_TGTEXP */
	N_("Reserved error message 27 (krb_mk_req)"),	/* krb_err.et:krb:KRBET_KRB_RES27 */
	N_("Reserved error message 28 (krb_mk_req)"),	/* krb_err.et:krb:KRBET_KRB_RES28 */
	N_("Reserved error message 29 (krb_mk_req)"),	/* krb_err.et:krb:KRBET_KRB_RES29 */
	N_("Reserved error message 30 (krb_mk_req)"),	/* krb_err.et:krb:KRBET_KRB_RES30 */
	N_("Can't decode authenticator (krb_rd_req)"),	/* krb_err.et:krb:KRBET_RD_AP_UNDEC */
	N_("Kerberos ticket expired (krb_rd_req)"),	/* krb_err.et:krb:KRBET_RD_AP_EXP */
	N_("Kerberos ticket not yet valid (krb_rd_req)"),	/* krb_err.et:krb:KRBET_RD_AP_NYV */
	N_("Repeated request (krb_rd_req)"),	/* krb_err.et:krb:KRBET_RD_AP_REPEAT */
	N_("Kerberos ticket is for wrong server (krb_rd_req)"),	/* krb_err.et:krb:KRBET_RD_AP_NOT_US */
	N_("Kerberos request inconsistent"),	/* krb_err.et:krb:KRBET_RD_AP_INCON */
	N_("Time is out of bounds (krb_rd_req)"),	/* krb_err.et:krb:KRBET_RD_AP_TIME */
	N_("Incorrect net address (krb_rd_req)"),	/* krb_err.et:krb:KRBET_RD_AP_BADD */
	N_("Kerberos protocol version mismatch (krb_rd_req)"),	/* krb_err.et:krb:KRBET_RD_AP_VERSION */
	N_("Invalid msg type (krb_rd_req)"),	/* krb_err.et:krb:KRBET_RD_AP_MSG_TYPE */
	N_("Message integrity error (krb_rd_req)"),	/* krb_err.et:krb:KRBET_RD_AP_MODIFIED */
	N_("Message out of order (krb_rd_req)"),	/* krb_err.et:krb:KRBET_RD_AP_ORDER */
	N_("Unauthorized request (krb_rd_req)"),	/* krb_err.et:krb:KRBET_RD_AP_UNAUTHOR */
	N_("Current password is null (get_pw_tkt)"),	/* krb_err.et:krb:KRBET_GT_PW_NULL */
	N_("Incorrect current password (get_pw_tkt)"),	/* krb_err.et:krb:KRBET_GT_PW_BADPW */
	N_("Protocol error (get_pw_tkt)"),	/* krb_err.et:krb:KRBET_GT_PW_PROT */
	N_("Error returned by KDC (get_pw_tkt)"),	/* krb_err.et:krb:KRBET_GT_PW_KDCERR */
	N_("Null Kerberos ticket returned by KDC (get_pw_tkt)"),	/* krb_err.et:krb:KRBET_GT_PW_NULLTKT */
	N_("Retry count exceeded (send_to_kdc)"),	/* krb_err.et:krb:KRBET_SKDC_RETRY */
	N_("Can't send request (send_to_kdc)"),	/* krb_err.et:krb:KRBET_SKDC_CANT */
	N_("Reserved error message 58 (send_to_kdc)"),	/* krb_err.et:krb:KRBET_KRB_RES58 */
	N_("Reserved error message 59 (send_to_kdc)"),	/* krb_err.et:krb:KRBET_KRB_RES59 */
	N_("Reserved error message 60 (send_to_kdc)"),	/* krb_err.et:krb:KRBET_KRB_RES60 */
	N_("Kerberos error: not all tickets returned"),	/* krb_err.et:krb:KRBET_INTK_W_NOTALL */
	N_("Incorrect password (get_in_tkt)"),	/* krb_err.et:krb:KRBET_INTK_BADPW */
	N_("Protocol error (get_in_tkt)"),	/* krb_err.et:krb:KRBET_INTK_PROT */
	N_("Other error (get_in_tkt)"),	/* krb_err.et:krb:KRBET_INTK_ERR */
	N_("Don't have Kerberos ticket-granting ticket (get_ad_tkt)"),	/* krb_err.et:krb:KRBET_AD_NOTGT */
	N_("You have no tickets cached"),	/* krb_err.et:krb:KRBET_NO_TKT_FIL */
	N_("Couldn't access ticket file (tf_util)"),	/* krb_err.et:krb:KRBET_TKT_FIL_ACC */
	N_("Couldn't lock ticket file (tf_util)"),	/* krb_err.et:krb:KRBET_TKT_FIL_LCK */
	N_("Bad ticket file format (tf_util)"),	/* krb_err.et:krb:KRBET_TKT_FIL_FMT */
	N_("tf_init not called before reading from ticket file (tf_util)"),	/* krb_err.et:krb:KRBET_TKT_FIL_INI */
	N_("Bad Kerberos name format (kname_parse)"),	/* krb_err.et:krb:KRBET_KNAME_FMT */
	N_("Generic kerberos error (kfailure)"),	/* krb_err.et:krb:KRBET_KFAILURE */
	N_("Principal in credential cache does not match desired name"),	/* gssapi_err_krb5.et:k5g:KG_CCACHE_NOMATCH */
	N_("No principal in keytab matches desired name"),	/* gssapi_err_krb5.et:k5g:KG_KEYTAB_NOMATCH */
	N_("Credential cache has no TGT"),	/* gssapi_err_krb5.et:k5g:KG_TGT_MISSING */
	N_("Authenticator has no subkey"),	/* gssapi_err_krb5.et:k5g:KG_NO_SUBKEY */
	N_("Context is already fully established"),	/* gssapi_err_krb5.et:k5g:KG_CONTEXT_ESTABLISHED */
	N_("Unknown signature type in token"),	/* gssapi_err_krb5.et:k5g:KG_BAD_SIGN_TYPE */
	N_("Invalid field length in token"),	/* gssapi_err_krb5.et:k5g:KG_BAD_LENGTH */
	N_("Attempt to use incomplete security context"),	/* gssapi_err_krb5.et:k5g:KG_CTX_INCOMPLETE */
	N_("Bad magic number for krb5_gss_ctx_id_t"),	/* gssapi_err_krb5.et:k5g:KG_CONTEXT */
	N_("Bad magic number for krb5_gss_cred_id_t"),	/* gssapi_err_krb5.et:k5g:KG_CRED */
	N_("Bad magic number for krb5_gss_enc_desc"),	/* gssapi_err_krb5.et:k5g:KG_ENC_DESC */
	N_("Sequence number in token is corrupt"),	/* gssapi_err_krb5.et:k5g:KG_BAD_SEQ */
	N_("Credential cache is empty"),	/* gssapi_err_krb5.et:k5g:KG_EMPTY_CCACHE */
	N_("Acceptor and Initiator share no checksum types"),	/* gssapi_err_krb5.et:k5g:KG_NO_CTYPES */
	N_("No @ in SERVICE-NAME name string"),	/* gssapi_err_generic.et:ggss:G_BAD_SERVICE_NAME */
	N_("STRING-UID-NAME contains nondigits"),	/* gssapi_err_generic.et:ggss:G_BAD_STRING_UID */
	N_("UID does not resolve to username"),	/* gssapi_err_generic.et:ggss:G_NOUSER */
	N_("Validation error"),	/* gssapi_err_generic.et:ggss:G_VALIDATE_FAILED */
	N_("Couldn't allocate gss_buffer_t data"),	/* gssapi_err_generic.et:ggss:G_BUFFER_ALLOC */
	N_("Message context invalid"),	/* gssapi_err_generic.et:ggss:G_BAD_MSG_CTX */
	N_("Buffer is the wrong size"),	/* gssapi_err_generic.et:ggss:G_WRONG_SIZE */
	N_("Credential usage type is unknown"),	/* gssapi_err_generic.et:ggss:G_BAD_USAGE */
	N_("Unknown quality of protection specified"),	/* gssapi_err_generic.et:ggss:G_UNKNOWN_QOP */
	N_("Local host name could not be determined"),	/* gssapi_err_generic.et:ggss:G_NO_HOSTNAME */
	N_("Hostname in SERVICE-NAME string could not be canonicalized"),	/* gssapi_err_generic.et:ggss:G_BAD_HOSTNAME */
	N_("Mechanism is incorrect"),	/* gssapi_err_generic.et:ggss:G_WRONG_MECH */
	N_("Token header is malformed or corrupt"),	/* gssapi_err_generic.et:ggss:G_BAD_TOK_HEADER */
	N_("Packet was replayed in wrong direction"),	/* gssapi_err_generic.et:ggss:G_BAD_DIRECTION */
	N_("Token is missing data"),	/* gssapi_err_generic.et:ggss:G_TOK_TRUNC */
	N_("Token was reflected"),	/* gssapi_err_generic.et:ggss:G_REFLECT */
	N_("Received token ID does not match expected token ID"),	/* gssapi_err_generic.et:ggss:G_WRONG_TOKID */
	NULL
};
